kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-cluster-role-binding-grp
subjects:
- kind: Group
  name: k8susers # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: dev-cluster-role
  apiGroup: rbac.authorization.k8s.io
